# Generated by Django 5.2.6 on 2025-09-25 13:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'conversation',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['id', 'created_at'], name='conversatio_id_dc87fb_idx'), models.Index(fields=['updated_at'], name='conversatio_updated_6c99b1_idx')],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sender_type', models.CharField(choices=[('user', 'User'), ('bot', 'Bot')], max_length=10)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chatbot_api.conversation')),
            ],
            options={
                'db_table': 'message',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['id', 'created_at'], name='message_id_130f60_idx'), models.Index(fields=['updated_at'], name='message_updated_be9f6b_idx')],
            },
        ),
    ]
